### ISSUE TITLE
"One in a million" server crash

### ISSUE THREAD

**Issue by ImGrumpy** [musiqpad/mqp-server#69]
Server crashed.  Log below.  Derp says it's one in a million, happens when the "user logs in just at the exact moment this thing checks for things or, disconnects just at the milisecond the pad advances".

```
[2016-04-28 15:31:40] SocketServer (debug) ::ffff:192.168.245.106 sent: {"type":"getUsers"}
[TypeError: Cannot read property 'uid' of null]
TypeError: Cannot read property 'uid' of null
    at C:\musiqpad-server\MQP_TRP\node_modules\mqp-server\socketserver\djqueue.js:237:43
    at C:\musiqpad-server\MQP_TRP\node_modules\mqp-server\socketserver\playlist.js:84:3
    at C:\musiqpad-server\MQP_TRP\node_modules\mqp-server\socketserver\YT.js:133:18
    at IncomingMessage.<anonymous> (C:\musiqpad-server\MQP_TRP\node_modules\mqp-server\socketserver\YT.js:85:18)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
[2016-04-28 15:31:41] SocketServer (info) Socket server listening on port 8082
```

**Comment by ImGrumpy** [comment]
Got another of these "one in a million" crashes.

```
[2016-05-20 15:28:39] SocketServer (debug) ::ffff:206.47.200.2 sent: {"type":"logout","data":{},"id":79}
[2016-05-20 15:28:39] SocketServer (debug) ::ffff:192.168.245.106 sent: {"type":"chat","data":{"message":"SylvieBi left."}}
[2016-05-20 15:28:39] SocketServer (debug) ::ffff:192.168.245.106 sent: {"type":"getUsers"}
[2016-05-20 15:28:39] SocketServer (debug) ::ffff:192.168.245.106 sent: {"type":"getUsers"}
[TypeError: Cannot read property 'uid' of null]
TypeError: Cannot read property 'uid' of null
    at C:\musiqpad-server\MQP_TRP\node_modules\mqp-server\socketserver\djqueue.js:237:43
    at C:\musiqpad-server\MQP_TRP\node_modules\mqp-server\socketserver\playlist.js:84:3
    at C:\musiqpad-server\MQP_TRP\node_modules\mqp-server\socketserver\YT.js:133:18
    at IncomingMessage.<anonymous> (C:\musiqpad-server\MQP_TRP\node_modules\mqp-server\socketserver\YT.js:85:18)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
[2016-05-20 15:28:41] SocketServer (info) Socket server listening on port 8082
```

**Comment by ImGrumpy** [comment]
Checking the logs, it looks like it also happened on May 12th.  Looks like it happened when a user was logging out each time.
